<?php
/** @var \Acx\CustomerPhone\Block\PhoneNum $block */
    $phoneNum = $block->getPhoneNum();
?>
<div class="field required">
    <label for="acx_phone_num" class="label"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
    <div class="control">
        <input type="text" name="acx_phone_num" id="acx_phone_num"
               value="<?php echo $phoneNum; ?>"
               title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>"
               class="input-text" value=" ?>">
    </div>
</div>




