<?php
/** @var \Acx\CustomerPhone\Block\PhoneNum $block */
    $phoneNum = $block->getPhoneNum();
?>
<div class="field required">
    <label for="phone_num" class="label"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
    <div class="control">
        <input type="text" name="phone_num" id="phone_num" value="<?php echo $phoneNum; ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="input-text" value=" ?>" data-validate="{required:true}">
    </div>
</div>




